// apps/migrator/src/app/navigation/navigation.component.ts
import { Component } from '@angular/core'
import { Store } from '@ngrx/store'
import { selectLanguage } from '@cypress-dx/migrator-state'

@Component({
  selector: 'cypress-dx-navigation',
  templateUrl: './navigation.component.html',
  styleUrls: ['./navigation.component.scss'],
})
export class NavigationComponent {
  migrationGuides = {
    protractor: { url: 'https://on.cypress.io/protractor-to-cypress' },
  }
  navLinks = [{ title: 'Cypress Docs', url: 'https://on.cypress.io/docs' }]

  selectedLanguage$ = this.store.select(selectLanguage)

  constructor(private readonly store: Store) {}
}

<nav class="flex max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 items-center">
  <div class="flex w-full justify-between items-center">
    <div class="flex-shrink-0 flex items-center">
      <a routerLink="/">
        <img src="assets/logo.png" alt="Cypress Logo" width="50" height="50" />
      </a>
      <a routerLink="/">
        <span class="text-xl font-bold mx-2">Migrator</span>
      </a>
    </div>

    <ul class="nav-list flex items-center sm:space-x-3 md:space-x-4 lg:space-x-8 leading-3 px-2" data-test="nav-list">
      <li>
        <a
          *ngIf="selectedLanguage$ | async as selectedLanguage"
          [href]="migrationGuides[selectedLanguage].url"
          class="dark:bg-gray-800 hover:underline bg-transparent dark:text-white py-2 rounded-md text-xs sm:text-sm font-medium capitalize"
        >
          {{ selectedLanguage }} Migration Guide
        </a>
      </li>
      <li *ngFor="let link of navLinks">
        <a
          [href]="link.url"
          class="dark:bg-gray-00 hover:underline bg-transparent dark:text-white py-2 rounded-md text-xs sm:text-sm font-medium"
        >
          {{ link.title }}
        </a>
      </li>
    </ul>
  </div>
</nav>
<hr />

// apps/translator/components/navigation.tsx
import { ReactElement } from 'react'
import Image from 'next/image'
import logo from '../public/logo.png'

import { useAppSelector, selectLanguage } from '../app'

const Navigation = (): ReactElement => {
  const selectedLanguage: string = useAppSelector(selectLanguage)
  const navLinks = [{ title: 'Cypress Docs', url: 'https://docs.cypress.io' }]
  const migrationGuides = {
    protractor: { url: 'https://on.cypress.io/protractor-to-cypress' },
  }

  return (
    <nav className="flex max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 items-center">
      <div className="flex w-full justify-between items-center">
        <div className="flex-shrink-0 flex items-center">
          <Image src={logo} alt="Cypress Logo" width="50" height="50" />
          <span className="text-xl font-bold mx-2">Translator</span>
        </div>

        <ul className="nav-list ml-10 flex items-center space-x-4">
          {migrationGuides[selectedLanguage] && (
            <li key={migrationGuides[selectedLanguage]}>
              <a
                href={migrationGuides[selectedLanguage].url}
                className="dark:bg-gray-800 hover:underline bg-transparent dark:text-white px-3 py-2 rounded-md text-sm font-medium capitalize"
              >
                {`${selectedLanguage} Migration Guide`}
              </a>
            </li>
          )}
          {navLinks.map((link) => (
            <li key={link.title}>
              <a
                href={link.url}
                className="dark:bg-gray-00 hover:underline bg-transparent dark:text-white px-3 py-2 rounded-md text-sm font-medium"
              >
                {link.title}
              </a>
            </li>
          ))}
        </ul>
      </div>
    </nav>
  )
}

export default Navigation
