// apps/translator/components/copyButton.tsx
import { ClipboardCopyIcon } from '@heroicons/react/outline'
import { ReactElement } from 'react'

const CopyButton = ({ copy }): ReactElement => {
  return (
    <div className="flex justify-end">
      <button
        type="button"
        title="Copy Button"
        className="inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        onClick={copy}
      >
        <ClipboardCopyIcon className="h-5 w-5 text-gray-500" />
        Copy
      </button>
    </div>
  )
}
export default CopyButton

// apps/migrator-new/src/app/copy-button/copy-button.component.ts
import { Component } from '@angular/core'
import { copyMigration } from '@cypress-dx/migrator-state'
import { Store } from '@ngrx/store'

@Component({
  selector: 'cypress-dx-copy-button',
  templateUrl: './copy-button.component.html',
  styleUrls: ['./copy-button.component.scss'],
})
export class CopyButtonComponent {
  constructor(private readonly store: Store) {}

  copy(): void {
    this.store.dispatch(copyMigration())
  }
}

<div class="flex justify-end">
  <button
    type="button"
    title="Copy Button"
    class="
      inline-flex
      items-center
      px-4
      py-2
      border border-gray-300
      shadow-sm
      text-sm
      font-medium
      rounded-md
      text-gray-700
      bg-white
      hover:bg-gray-50
      focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500
    "
    (click)="copy()"
  >
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="h-6 w-6 text-gray-500"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3"
      />
    </svg>
    Copy
  </button>
</div>
