// apps/migrator-new/src/app/diff-toggle/diff-toggle.component.ts
import { Component } from '@angular/core'
import { selectDisplayDiff, toggleDisplayDiff } from '@cypress-dx/migrator-state'
import { Store } from '@ngrx/store'

@Component({
  selector: 'cypress-dx-diff-toggle',
  templateUrl: './diff-toggle.component.html',
  styleUrls: ['./diff-toggle.component.scss'],
})
export class DiffToggleComponent {
  diffToggle$ = this.store.select(selectDisplayDiff)

  constructor(private readonly store: Store) {}

  toggle(): void {
    console.log('toggle')
    this.store.dispatch(toggleDisplayDiff())
  }
}

<button
  type="button"
  (click)="toggle()"
  [class.bg-green-300]="diffToggle$ | async"
  [class.bg-gray-200]="(diffToggle$ | async) === false"
  class="
    relative
    inline-flex
    flex-shrink-0
    h-6
    w-11
    border-2 border-transparent
    rounded-full
    cursor-pointer
    transition-colors
    ease-in-out
    duration-200
    focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500
  "
  role="switch"
  aria-checked="false"
>
  <span class="sr-only">Display Toggle</span>
  <!-- Enabled: "translate-x-5", Not Enabled: "translate-x-0" -->
  <span
    aria-hidden="true"
    class="
      pointer-events-none
      inline-block
      h-5
      w-5
      rounded-full
      bg-white
      shadow
      transform
      ring-0
      transition
      ease-in-out
      duration-200
    "
    [class.translate-x-5]="diffToggle$ | async"
  ></span>
</button>

// apps/migrator/components/diffToggle.tsx
import { Switch } from '@headlessui/react'
import { selectDisplayDiff, setDisplayDiff, useAppDispatch, useAppSelector } from '../app'

function classNames(...classes: string[]) {
  return classes.filter(Boolean).join(' ')
}

const DiffToggle = () => {
  const enabled = useAppSelector(selectDisplayDiff)
  const dispatch = useAppDispatch()
  const setEnabled = () => dispatch(setDisplayDiff(!enabled))

  return (
    <Switch.Group as="div" className="flex items-center pl-4">
      <Switch
        checked={enabled}
        onChange={() => setEnabled()}
        className={classNames(
          enabled ? 'bg-jade-300' : 'bg-gray-200',
          'relative inline-flex flex-shrink-0 h-6 w-11 border-2 border-transparent rounded-full cursor-pointer transition-colors ease-in-out duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-jade-400',
        )}
      >
        <span
          aria-hidden="true"
          className={classNames(
            enabled ? 'translate-x-5' : 'translate-x-0',
            'pointer-events-none inline-block h-5 w-5 rounded-full bg-white shadow transform ring-0 transition ease-in-out duration-200',
          )}
        />
      </Switch>
      <Switch.Label as="span" className="ml-3 sm:text-md font-medium text-gray-900">
        Display Diff Coloring
      </Switch.Label>
    </Switch.Group>
  )
}
export default DiffToggle
