// apps/migrator-new/src/app/migration-diff/migration-diff.component.ts
import { Component } from '@angular/core'
import { selectDiffApiItems, selectShouldShowDetails } from '@cypress-dx/migrator/migrator-state'
import { Store } from '@ngrx/store'

@Component({
  selector: 'cypress-dx-migration-diff',
  templateUrl: './migration-diff.component.html',
  styleUrls: ['./migration-diff.component.scss'],
})
export class MigrationDiffComponent {
  showDetails$ = this.store.select(selectShouldShowDetails)
  diffItems$ = this.store.select(selectDiffApiItems)

  constructor(private readonly store: Store) {}
}

<div *ngIf="showDetails$ | async" class="md:w-full transition duration-500 ease-in-out" data-test="more-details">
  <h2 class="text-3xl leading-6 font-bold text-gray-900 my-4 capitalize">More details about your migration:</h2>
  <hr />
  <!-- <ErrorAlerts /> -->
  <div class="flex justify-between">
    <div data-test="api-details">
      <p class="py-4">
        The following Cypress API items were found in the migrated code. For more detailed information about each item,
        click the link to its page within our documentation.
      </p>
      <ul class="list-inside list-none mb-4" data-test="api-details-list">
        <li *ngFor="let item of diffItems$ | async" class="flex items-center">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-6 w-6 ml-2 -mr-1"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M13 9l3 3m0 0l-3 3m3-3H8m13 0a9 9 0 11-18 0 9 9 0 0118 0z"
            />
          </svg>
          <a class="ml-2 text-green-400 hover:text-green-500" [href]="item?.url" rel="noreferrer" target="_blank">
            {{ item?.command }}
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>

// apps/migrator/components/migrationDiff.tsx
import Link from 'next/link'
import Image from 'next/image'
import { ReactElement } from 'react'
import { selectDiffApiItems, shouldShowDetails, useAppSelector } from '../app'
import { ErrorAlerts } from '.'

const MigrationDiff = (): ReactElement => {
  const diff = useAppSelector(selectDiffApiItems)
  const showDetails = useAppSelector(shouldShowDetails)

  return (
      <div
        className={`md:w-full transition duration-500 ease-in-out mt-20 relative ${showDetails ? 'opacity-100' : 'opacity-0'}`}
        data-test="more-details"
      >
        <ErrorAlerts />
        {diff.length > 0 ? (
            <div className="flex w-full">
              <div className="w-1/2">
                <h2 className="text-2xl leading-10 font-bold text-gray-900 max-w-lg">
                  Great! The following Cypress commands were found in the migrated code.
                </h2>
                <p className="text-gray-600 py-4 max-w-md">
                  For more detailed information about each item, click the link to its page within our documentation.
                </p>
                <Link href="/migrations" passHref>
                  <button
                      type="button"
                      className="px-6 py-3 my-4 text-base font-medium rounded-md shadow-sm text-indigo-500 bg-indigo-50 transition duration-300 ease-in-out transform hover:-translate-y-0 hover:scale-105"
                      >
                        See all Protractor Migrations
                  </button>
                </Link>
              </div>
              <div className="bg-white w-1/2" data-test="api-details">
                <ul className="list-inside list-none divide-y divide-gray-50 p-6 rounded shadow" data-test="api-details-list">
                  {diff.map((d, i: number) => (
                    <li className="flex items-center py-4 first:pt-0 last:pb-0" key={i}>
                      <Image src="/docs_icon.svg" alt="" width="40" height="40" />
                      <a
                        className="ml-2 text-gray-900 hover:text-indigo-400 hover:underline"
                        href={d.url}
                        rel="noreferrer"
                        target="_blank"
                      >
                        {d.command}
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          ) : null}
      </div>
  )
}
export default MigrationDiff
