// apps/migrator/components/languagePills.tsx
import { ArrowRightIcon } from '@heroicons/react/solid'
import React, { ReactElement } from 'react'
import { selectLanguage, useAppSelector } from '../app'

const LanguagePills = (): ReactElement => {
  const selectedLanguage = useAppSelector(selectLanguage)
  return (
    <div className="grid md:grid-cols-3 gap-4 sm:grid-cols-1">
      <div className="md:col-start-2 flex justify-center">
        <span className="px-3 py-2 rounded-full text-sm font-medium bg-red-300 text-red-800 capitalize">
          {selectedLanguage}
        </span>
        <ArrowRightIcon className="h-5 w-5 mx-4 my-2 text-gray-500" />
        <span className="px-3 py-2 rounded-full text-sm font-medium bg-green-300 text-green-800">Cypress</span>
      </div>
    </div>
  )
}
export default LanguagePills

// apps/migrator/src/app/home/language-pills/language-pills.component.ts
import { Component } from '@angular/core'
import { selectLanguage } from '@cypress-dx/migrator-state'
import { Store } from '@ngrx/store'

@Component({
  selector: 'cypress-dx-language-pills',
  templateUrl: './language-pills.component.html',
  styleUrls: ['./language-pills.component.scss'],
})
export class LanguagePillsComponent {
  selectedLanguage$ = this.store.select(selectLanguage)
  constructor(private readonly store: Store) {}
}

<div class="grid md:grid-cols-3 gap-4 sm:grid-cols-1">
  <div class="md:col-start-2 flex justify-center">
    <span class="px-3 py-2 rounded-full text-sm font-medium bg-red-300 text-red-800 capitalize">
      {{ selectedLanguage$ | async }}
    </span>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="h-5 w-5 mx-4 my-2 text-gray-500"
      viewBox="0 0 20 20"
      fill="currentColor"
    >
      <path
        fill-rule="evenodd"
        d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
        clip-rule="evenodd"
      />
    </svg>
    <span class="px-3 py-2 rounded-full text-sm font-medium bg-green-300 text-green-800">Cypress</span>
  </div>
</div>
